-- Insert mock data for testing
INSERT INTO conversations (
  user_name,
  user_email,
  profile_name,
  profile_url,
  conversation_summary,
  follow_up_text,
  date_met,
  meeting_event,
  future_potential,
  follow_up_priority,
  follow_up_suggestion
) VALUES 
(
  'Amber',
  'amber@gmail.com',
  'Yilun Sun',
  'https://www.linkedin.com/in/yilun-s/',
  'Discussed AI innovations and career growth opportunities in machine learning.',
  'Hi Yilun, it was great meeting you at the conference. I''d love to continue our conversation about AI collaboration opportunities.',
  '2023-10-15',
  'AI Innovation Conference 2023',
  'High potential for collaboration on AI projects and research initiatives.',
  'High',
  'Reach out to discuss potential AI collaboration and research opportunities.'
),
(
  'Amber',
  'amber@gmail.com',
  'Sarah Johnson',
  'https://www.linkedin.com/in/sarah-johnson/',
  'Talked about marketing strategies and digital transformation in the healthcare industry.',
  'Hi Sarah, thanks for the insightful discussion about marketing trends. Let''s connect to explore potential partnerships.',
  '2023-10-10',
  'Marketing Summit 2023',
  'Medium potential for business collaboration in healthcare marketing.',
  'Medium',
  'Send a follow-up message about marketing collaboration opportunities.'
),
(
  'Amber',
  'amber@gmail.com',
  'Michael Chen',
  'https://www.linkedin.com/in/michael-chen-dev/',
  'Explored software architecture patterns and cloud migration strategies.',
  'Hi Michael, enjoyed our discussion about microservices architecture. Would love to dive deeper into your cloud migration experience.',
  '2023-10-08',
  'Tech Meetup - Cloud Architecture',
  'Strong potential for technical collaboration and knowledge sharing.',
  'High',
  'Connect to discuss cloud architecture and share technical insights.'
),
(
  'Amber',
  'amber@gmail.com',
  'Emily Rodriguez',
  'https://www.linkedin.com/in/emily-rodriguez/',
  'Discussed startup funding strategies and investor relations.',
  'Hi Emily, your insights on startup funding were invaluable. Let''s stay connected for future networking opportunities.',
  '2023-10-05',
  'Startup Networking Event',
  'Good potential for startup ecosystem collaboration.',
  'Medium',
  'Follow up about startup ecosystem and potential partnerships.'
),
(
  'Amber',
  'amber@gmail.com',
  'David Kim',
  'https://www.linkedin.com/in/david-kim/',
  'Talked about product management methodologies and user experience design.',
  'Hi David, your product management insights were fantastic. I''d love to learn more about your UX design process.',
  '2023-10-03',
  'Product Management Workshop',
  'High potential for product development collaboration.',
  'High',
  'Connect to discuss product management and UX design strategies.'
),
(
  'Amber',
  'amber@gmail.com',
  'Lisa Wang',
  'https://www.linkedin.com/in/lisa-wang/',
  'Explored data science applications in financial services and risk management.',
  'Hi Lisa, your expertise in financial data science is impressive. Let''s explore potential collaboration opportunities.',
  '2023-09-28',
  'Data Science in Finance Conference',
  'Excellent potential for fintech collaboration and research.',
  'High',
  'Reach out to discuss fintech data science opportunities.'
),
(
  'Amber',
  'amber@gmail.com',
  'James Wilson',
  'https://www.linkedin.com/in/james-wilson/',
  'Discussed blockchain technology and cryptocurrency market trends.',
  'Hi James, your blockchain insights were fascinating. I''d love to stay updated on your crypto research.',
  '2023-09-25',
  'Blockchain Technology Summit',
  'Medium potential for blockchain collaboration.',
  'Medium',
  'Follow up about blockchain technology and crypto trends.'
),
(
  'Amber',
  'amber@gmail.com',
  'Maria Garcia',
  'https://www.linkedin.com/in/maria-garcia/',
  'Talked about sustainable technology solutions and green energy initiatives.',
  'Hi Maria, your passion for sustainable tech is inspiring. Let''s connect to explore green technology opportunities.',
  '2023-09-22',
  'Green Technology Expo',
  'Good potential for sustainability collaboration.',
  'Medium',
  'Connect to discuss sustainable technology initiatives.'
),
(
  'Amber',
  'amber@gmail.com',
  'Alex Thompson',
  'https://www.linkedin.com/in/alex-thompson/',
  'Explored cybersecurity best practices and threat intelligence sharing.',
  'Hi Alex, your cybersecurity expertise is impressive. I''d love to learn more about your security strategies.',
  '2023-09-20',
  'Cybersecurity Conference',
  'High potential for security collaboration and knowledge sharing.',
  'High',
  'Reach out to discuss cybersecurity strategies and best practices.'
),
(
  'Amber',
  'amber@gmail.com',
  'Rachel Green',
  'https://www.linkedin.com/in/rachel-green/',
  'Discussed remote work strategies and team collaboration tools.',
  'Hi Rachel, your remote work insights were valuable. Let''s stay connected for future collaboration opportunities.',
  '2023-09-18',
  'Remote Work Summit',
  'Medium potential for workplace collaboration.',
  'Low',
  'Follow up about remote work strategies and team collaboration.'
);
